/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonController: typeof import('./src/components/ButtonController.vue')['default']
    CategorySlider: typeof import('./src/components/CategorySlider.vue')['default']
    CollectionSlider: typeof import('./src/components/CollectionSlider.vue')['default']
    CookieConsent: typeof import('./src/components/CookieConsent.vue')['default']
    DefaultFooter: typeof import('./src/components/DefaultFooter.vue')['default']
    DefaultHeader: typeof import('./src/components/DefaultHeader.vue')['default']
    Disclaimer: typeof import('./src/components/Disclaimer.vue')['default']
    Error: typeof import('./src/components/Error.vue')['default']
    FollowUs: typeof import('./src/components/FollowUs.vue')['default']
    FooterBenefit: typeof import('./src/components/FooterBenefit.vue')['default']
    FullWidthBanner: typeof import('./src/components/FullWidthBanner.vue')['default']
    HeaderContentCategory: typeof import('./src/components/HeaderContentCategory.vue')['default']
    HeaderContentSpreadList: typeof import('./src/components/HeaderContentSpreadList.vue')['default']
    HeaderContentThumbList: typeof import('./src/components/HeaderContentThumbList.vue')['default']
    HeaderNavMobile: typeof import('./src/components/HeaderNavMobile.vue')['default']
    HeaderSubNavListItem: typeof import('./src/components/HeaderSubNavListItem.vue')['default']
    Highlights: typeof import('./src/components/Highlights.vue')['default']
    KeyVisual: typeof import('./src/components/KeyVisual.vue')['default']
    LeftVisualRightContentBanner: typeof import('./src/components/LeftVisualRightContentBanner.vue')['default']
    LeftVisualRightContentSlider: typeof import('./src/components/LeftVisualRightContentSlider.vue')['default']
    PdListNormalItem: typeof import('./src/components/PdListNormalItem.vue')['default']
    PdListPromotionItem: typeof import('./src/components/PdListPromotionItem.vue')['default']
    PopupContainer: typeof import('./src/components/PopupContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopList: typeof import('./src/components/ShopList.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Template: typeof import('./src/components/template.vue')['default']
  }
}
